spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/testdb
    username: testUser
    password: testUserPassword
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        default_schema: public
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: false
  liquibase:
    change-log: classpath:db/changelog/v1/changelog-v1.yaml